import '@mantine/core/styles.css';
import localFont from "next/font/local";
import "../globals.css";
import "../fonts/icons/css/all.css"
import GetUser from "./components/GetUser";
import { Roboto } from 'next/font/google'
import { MantineProvider, Container } from '@mantine/core';
import SideNav from './components/SideNav.jsx'
import MobileNav from './components/MobileNav.jsx'


const roboto = Roboto({weight: '400' , subsets: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}`}
      >
        <MantineProvider>
          <GetUser/>
          <div className='flex-col'>
            <Container size='responsive'>
              <div className='flex gap-x-2'>
                <div className='hidden md:block'><SideNav/></div>
                <div className='grow max-w-[1400px] mx-auto'>
                  {children}
                </div>
              </div>
            </Container>
            <div className='  fixed bottom-0 block md:hidden'><MobileNav/></div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
