import '@mantine/core/styles.css';
import localFont from "next/font/local";
import "../globals.css";
import "../fonts/icons/css/all.css"
import GetUser from "./components/GetUser";
import { Roboto } from 'next/font/google'
import { MantineProvider } from '@mantine/core';
import SideNav from './components/SideNav.jsx'
import MobileNav from './components/MobileNav.jsx'


const roboto = Roboto({weight: '400' , subsets: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}`}
      >
        <MantineProvider>
          <GetUser/>
          <div className='flex-col '>
            <div className='flex'>
              <div className='hidden md:block'><SideNav/></div>
              <div>
                {children}
              </div>
            </div>
            <div className='fixed bottom-0 block md:hidden '><MobileNav/></div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
